//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2P借貸_MVC.Areas.Standard_Case.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class P2P借貸平台_2Entities1 : DbContext
    {
        public P2P借貸平台_2Entities1()
            : base("name=P2P借貸平台_2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Standard_case> Standard_case { get; set; }
        public virtual DbSet<Standard_case_details> Standard_case_details { get; set; }
        public virtual DbSet<Standard_case_fraction> Standard_case_fraction { get; set; }
        public virtual DbSet<Standard_case_history> Standard_case_history { get; set; }
        public virtual DbSet<Standard_case_talk> Standard_case_talk { get; set; }
        public virtual DbSet<BasicInfo> BasicInfo { get; set; }
    }
}
