//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2P借貸_MVC.Areas.Standard_Case.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Standard_case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Standard_case()
        {
            this.Standard_case_details = new HashSet<Standard_case_details>();
            this.Standard_case_history = new HashSet<Standard_case_history>();
            this.Standard_case_talk = new HashSet<Standard_case_talk>();
        }

        [DisplayName("標案編號")]
        public int StandcaseID { get; set; }
        [DisplayName("主辦者編號")]
        public Nullable<int> MemberSponer { get; set; }
        [DisplayName("可參加人數")]
        public Nullable<int> Memberprople { get; set; }
        [DisplayName("標案總金額")]
        public Nullable<int> Casemoney { get; set; }
        [DisplayName("標案期數")]
        public Nullable<int> CaseMonth { get; set; }
        [DisplayName("標案開始日")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
        public Nullable<System.DateTime> CaseFirstday { get; set; }
        [DisplayName("標案結束日")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
        public Nullable<System.DateTime> CaseEndnay { get; set; }
        [DisplayName("預計匯款日")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
        public Nullable<System.DateTime> MoneyForday { get; set; }
        public Nullable<bool> CaseStatus { get; set; }
        public Nullable<bool> CaseStatus2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Standard_case_details> Standard_case_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Standard_case_history> Standard_case_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Standard_case_talk> Standard_case_talk { get; set; }
        public virtual BasicInfo BasicInfo { get; set; }
    }
}
