//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2P借貸_MVC.Areas.Standard_Case.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard_case_history
    {
        public int SID { get; set; }
        public int StandcaseID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string MemberAccount { get; set; }
        public Nullable<System.DateTime> Remittancetime { get; set; }
    
        public virtual Standard_case Standard_case { get; set; }
    }
}
