//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2P借貸_MVC.Areas.AreaCollater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollaterDetail
    {
        public int CollateralID { get; set; }
        public string MemberName { get; set; }
        public string CollateralName { get; set; }
        public int MemberID { get; set; }
        public decimal interestrate { get; set; }
        public string CollateralEX { get; set; }
        public byte[] Collateralimage { get; set; }
        public decimal loanPrice { get; set; }
        public string Collateralsituation { get; set; }
        public string Collateraluse { get; set; }
        public int investmentID { get; set; }
    
        public virtual BasicInfo BasicInfo { get; set; }
    }
}
